### PR TITLE
Add some info to readme to help users understand project

### PR DESCRIPTION
**Pull request by HeshanPunch**
- Filled summary on readme

### CODE REVIEW

**Comment by Jarish85** [comment]
good gob

**Review by noor741 — COMMENTED** [review]
Good jon prof!

**Comment by davidpal3c** [comment]
good job =)

**Comment by LunaroySimon** [comment]
good job!

**Comment by KyleJamesD** [comment]
awesome job

**Comment by davidpal3c** [comment]
readme file opens nicely

**Review by NikKonakov — APPROVED** [review]
Here you go!

**Review by LunaroySimon — APPROVED** [review]

**Review by glconde — APPROVED** [review]
A

**Review by noor741 — APPROVED** [review]
nailed it

**Review by joshualoui — APPROVED** [review]

**Review by Jarish85 — APPROVED** [review]
yes yes yes

**Comment by sLine03** [comment]
W

**Review by JohnPaolo18 — COMMENTED** [review]
good job :)

**Pull request merged**
